### ISSUE TITLE
Create or find a crystal implementation of 2FA

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#111]
We are going to need a crystal version of a two factor authentication library that we can use to protect transactions - needs to be compatible with Authy and Google authenticator

**Comment by tbrand** [comment]
Is this duplicated with https://github.com/SushiCoinHQ/SushiCoin/issues/97 ?

**Comment by kingsleyh** [comment]
I think not a duplicate - as this one is about building or finding a 2FA library - I think none exists for Crystal actually - so I guess we will need to build it. The other one #97 is about integrating 2FA with sushi - which I think is a different piece of work to building a 2FA

**Comment by kingsleyh** [comment]
I have created a Crystal 2FA TOTP library we can use in SushiChain here: https://github.com/SushiChain/crystal-two-factor-auth
