### ISSUE TITLE
Fix E2E tests - they fail intermittently

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#114]
Out of many runs the E2E tests fail intermittently

see TeamCity server history:  https://sushicoin.xyz/viewType.html?buildTypeId=SushiCoin_1MainBuild&branch_SushiCoin=%3Cdefault%3E&tab=buildTypeStatusDiv

<img width="1140" alt="screen shot 2018-03-18 at 22 00 18" src="https://user-images.githubusercontent.com/103770/37571682-d76f6484-2af7-11e8-9c63-670a0762d0fa.png">

**Comment by tbrand** [comment]
Fixed
