### ISSUE TITLE
Fees - consider allowing transactions to be picked up if more fee paid

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#134]
Currently the fees are fixed - I think we should consider the following 3 points:

1. If a fee greater than the minimum fee is supplied the transaction could be picked up by a miner sooner than those with lower fees. See this for how bitcoin does it (https://en.bitcoin.it/wiki/Transaction_fees)

2. Provide a mechanism to change the fees without a hard fork (so we can change the fees more easily)

3. (In the future) Allow fees to be voted by nodes (e.g. each node could vote to increase/decrease the amount for a particular fee - this would need some thought about how to make the voting fair - probably it could be a built in dApp - where a voting transaction is sent from the wallet (WIF) that runs the node - and the fee is decided by a majority - it could also be weighted by the popularity of the node e..g how many transactions/blocks it processes and/or by the amount of SHARI its wallet etc)

**Comment by tbrand** [comment]
It's already accepted. But not sort for the amount of the fee.
