### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#136]
develop a REST API for external developers - so that they can use any language they like to communicate with the node. Some of the operations should probably be streaming responses e.g. fetching the full blockchain. It would also be cool to have a websockets version along side the REST API which can push the new block creation out over the websocket - and perhaps other things as well might be nice as a websocket in addition to the REST API. This way developers could also use the websocket to listen for a new block and write code that checks the transactions for a specific action in a similar way to how the external dapps work.

This could be built into the core - or for flexibility it could be an external dapp - so we can update it without a release if required and give the opportunity for it to be turned off on a node.

I guess both approaches have their pros and cons. 

--UPDATE

I propose the following API 

### Blockchain

| Method  | Resource                                                  | Response    | Notes                               | 
| ------- |:----------------------------------------------------------|:-----------:|-------------------------------------|        
| GET     | api/blockchain                                            | Json Stream | full blockchain                     |
| GET     | api/blockchain/size                                       | Json        | blockchain size                     |
| GET     | api/blockchain/block/[index]                              | Json        | full block at index                 |
| GET     | api/blockchain/block/[index]/header                       | Json        | block header at index               |
| GET     | api/blockchain/block/transaction/[transaction_id]         | Json        | full block containing txn id        |
| GET     | api/blockchain/block/transaction/[transaction_id]/header  | Json        | block header containing txn id      |   

### Transactions

| Method  | Resource                                                  | Response       | Notes                               | 
| ------- |:----------------------------------------------------------|:--------------:|-------------------------------------|        
| GET     | api/transactions/block/[index]                            | Json           | transactions in block               |
| GET     | api/transactions/[transaction_id]                         | Json           | transaction for supplied txn id     |
| GET     | api/transactions/address/[address]                        | Json Paginated | transactions for address            |
| GET     | api/transactions/confirmations/[transaction_id]           | Json           | number confirmations for txn id     |
| GET     | api/transactions/fees                                     | Json           | fees                                |
| POST    | api/transactions                                          | Json           | post json body containing options   |

#### Create transaction

* POST api/transactions
* post body

```json
{"fee": 1,
 "amount": 100,
 "address": "some-address"
}
```

|Option  | Presence    | Notes |
| ----   | ----        | ---   |
| fee    | Mandatory   | always present |
| amount | Conditional | mandatory if action requires an amount e.g. send |
| address| Conditional | mandatory if action requires an address e.g. send (either address or domain)|
| domain | Conditional | mandatory if action requires an address e.g. send (either address or domain)|
| action | Mandatory   | always present |
| message| Conditional | mandatory if action requires a message e.g. dapps |

* API should respond with an error as json based on these rules. (If we can't enforce these rules easily then we could make some of them Optional and the transaction will be rejected later on)

* The post transaction api should be able to be used for creating transactions for different actions for use with dapps for example.

#### Pagination

For responses that need it - pagination could be something like this:

```
GET api/transactions/address/[address]?page=1&per_page=20
```

* default page = last page
* default per page = 20

##### Metadata

It is helpful to have medatdata for pagination:

```
GET api/transactions/address/[address]?page=1&per_page=20&metadata=true
```

* default metadata = false

A response with metadata (with semantic web style links):

```json
{"metadata":{
  "page": 2,
  "per_page": 20,
  "page_count": 20,
  "total_count": 200,
  "links": [
    {"current": "api/transactions/address/[address]?page=2&per_page=20"},
    {"first": "api/transactions/address/[address]?page=0&per_page=20"}
    {"prev": "api/transactions/address/[address]?page=1&per_page=20"}
    {"next": "api/transactions/address/[address]?page=3&per_page=20"}
    {"last": "api/transactions/address/[address]?page=10&per_page=20"}
  ]
},
"transactions": []
}
```

### Wallet

| Method  | Resource                                                  | Response       | Notes                               | 
| ------- |:----------------------------------------------------------|:--------------:|-------------------------------------|        
| GET     | api/wallet/amount/confirmed/[address]                     | Json           | confirmed amount for address        | 
| GET     | api/wallet/amount/unconfirmed/[address]                   | Json           | unconfirmed amount for address      |

**Comment by kingsleyh** [comment]
I think in addition we could also have a couple of websocket endpoints:

* websocket for when new block is pushed - so the Json block is sent
* websocket for when a new transaction happens for an address

**Comment by tbrand** [comment]
Please open other issues for websocket and POST REST APIs.
