### ISSUE TITLE
Send/Receive messages on Chord

### ISSUE THREAD

**Issue by tbrand** [SushiChain/SushiChain#164]
This realizes realtime applications on the blockchain.

**Comment by kingsleyh** [comment]
Could this be used for a blockchain chat app?

**Comment by tbrand** [comment]
Exactly, but this is just an idea. I don't image the implementation for now.

**Comment by kingsleyh** [comment]
sounds awesome - looking forward to this

**Comment by kingsleyh** [comment]
done
