### ISSUE TITLE
Transaction should have failed - when sending to yourself

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#173]
I have not enough SHARI in the wallet to make this transaction  - however it says it was accepted - it should have been reject for insufficient amount of SHARI - tested in master and transaction-pending

```
  showing amount of each token for VDBkYWQxZjZlZjllOTAzYzNiODQ0NmZkZTI4NDBhYmMzYjUxYThjM2E1ZjNkODlj.
  confirmed: false

  + -------------------- - -------------------- +
  |                token |               amount |
  | -------------------- | -------------------- |
  |                SHARI |                    0 |
  + -------------------- - -------------------- +
```

```
{"status":"accepted","transaction":{"id":"25059bf01f714ee57ec6d82e06a4cda9cc4dcabc80bfddb97d3b3bc5dd747b88","action":"send","senders":[{"address":"VDBkYWQxZjZlZjllOTAzYzNiODQ0NmZkZTI4NDBhYmMzYjUxYThjM2E1ZjNkODlj","public_key":"48c45b7e45cd415187216452fa22523e002ca042c2bd7205484f29201c3d5806f90e7aeebad37e3fbe01286c25d4027d3f3fec7b5647eff33c07ebd287b57242","amount":10000000000,"fee":1}],"recipients":[{"address":"VDBkYWQxZjZlZjllOTAzYzNiODQ0NmZkZTI4NDBhYmMzYjUxYThjM2E1ZjNkODlj","amount":10000000000}],"message":"","token":"SHARI","prev_hash":"a758f45cb39f6991c6b9ec226bd30da100bde5b973f9a830dcbb696c305827ff","sign_r":"4f1459b12b4d422b2c20c7e401a433f78105a75865d9fa3f2a2e616711aea4ec","sign_s":"48bfe7416ffdd1bf6d3f253b82cf81a9c25448270a5880e488a22520c13e8ec6"}}
```
The amount did not seem to be applied to the wallet - so don't know what happened to it

**Comment by tbrand** [comment]
Please let me know how to launch `sushid`, `sushim` and `sushi`. (We should add `ISSUE_TEMPLATE`.)

## Executed commands

I try to recreate the situation by

- **sushid**
```
> SC_DEBUG=true ./bin/sushid -w wallets/testnet-0.json --private --testnet
```

- **sushim**
```
> ./bin/sushim -n http://localhost:3000 -w wallets/testnet-0.json --testnet
```

- **sushi**
```
> ./bin/sushi tx create -n http://localhost:3000 -w wallets/testnet-1.json -m 0 -f 1 -a VDAxYjk3ODA0YmEzMTQwNjI0NDBiMzhkMzE4MTdlYzQwNjYxMzZiZjMyNzEwZTBh
```

Then I confirmed the transaction's status after a block was mined
```
> ./bin/sushi tx tx -t 20b59829d791e40aa432d140603577e9c5a9d452d47906062b40ed6fa9778ef4 -n http://localhost:3000
the transaction was rejected
the reason: sender has not enough token(SHARI). sender has 0 + 0 but try to pay 1
```
It means that sender has 0 (current amount) + 0 (received amount) but try to pay 1 (fee)
So we successfully prevent to import the invalid transaction I think.

Sender sending tokens to himself/herself is useful for many cases.
For example, in token.cr dApp, it uses it to know how much token will user create without any tokens except fees. [here](https://github.com/SushiChain/SushiChain/blob/master/src/core/dapps/build_in/token.cr#L42-L46)

So I think we should keep the feature for the dApps extensibility.

**Comment by tbrand** [comment]
What is this status? Can I close?

**Comment by kingsleyh** [comment]
UPDATE

```
current configuration is for: 'w2' in file /Users/kings/.sushi/config
configuration is Enabled
--------------------
connect_node:	http://testnet.sushichain.io:3000
wallet_path:	/Users/kings/sc-wallets/w2.json
is_testnet:	true
is_private:	false
bind_host:	0.0.0.0
bind_port:	3000
threads:	1
encrypted:	false
```

I have only 9.999 SUSHI in w2:

```
sushi wt amount

  showing amount of each token for VDA2YWQ0Y2JkMzE3NmVmNWNhYTNkNTg3ZjA5ZjZiZmM3NzUzNmY4MGM3ZTM2NTIw.
  confirmed: true

  + -------------------- - -------------------- +
  |                token |               amount |
  | -------------------- | -------------------- |
  |                SUSHI |                9.999 |
  + -------------------- - -------------------- +
```

But I create a transaction that sends 20 from w2 to w2 (sending to itself)

The transaction is accepted:

```
{"status":"accepted","transaction":{"id":"e0eda31aac4c9f0408e4cec6874bcb351a86d96dee592e8025f196af061762e8","action":"send","senders":[{"address":"VDA2YWQ0Y2JkMzE3NmVmNWNhYTNkNTg3ZjA5ZjZiZmM3NzUzNmY4MGM3ZTM2NTIw","public_key":"a7cd1c6660342389ee8856b11c0246f4d21e139fb97e6c9a06edf34c39b094b4cd764950694fc37834d509d7193f9e0e192f2774c7187ea1b5731466a42039a8","amount":2000000000,"fee":10000,"sign_r":"27f5be5a29d589f3b22d0b830652cd152a8b65c8ea0d39efab28ff37dea027ab","sign_s":"ba801d3d1716118ac884ec50b3f65389e897822784b3abc83b8e633cd635891f"}],"recipients":[{"address":"VDA2YWQ0Y2JkMzE3NmVmNWNhYTNkNTg3ZjA5ZjZiZmM3NzUzNmY4MGM3ZTM2NTIw","amount":2000000000}],"message":"","token":"SUSHI","prev_hash":"8d78702370629bc726555c557f92bc3d2258094782c5e4fbfa0021ded17654e8","scaled":1}}
```

But I expected this transaction to be rejected - because I do not have enough SUSHI to send from w2 to itself.

**Comment by kingsleyh** [comment]
The wallet amount did not change - but what I find strange is that the address does show that the transaction is associated with the address - just the amount did not get added to the wallet - if you look at the transactions for the address it appears:

http://testnet.sushichain.io:3000/api/v1/address/VDA2YWQ0Y2JkMzE3NmVmNWNhYTNkNTg3ZjA5ZjZiZmM3NzUzNmY4MGM3ZTM2NTIw/transactions

Something about this does not seem right. What do you think? I think being able to send a transaction to yourself is good but not sure about this particular scenario. Maybe it's ok - If you think it's fine then I'm ok with it too.

**Comment by tbrand** [comment]
The amount had not been changed? That's strange. I thought the amount should be "9.9989" (by the fee).

**Comment by kingsleyh** [comment]
Hi - I just checked again - yes you are right the amount was altered according to the fee:

```  showing amount of each token for VDA2YWQ0Y2JkMzE3NmVmNWNhYTNkNTg3ZjA5ZjZiZmM3NzUzNmY4MGM3ZTM2NTIw.
  confirmed: true

  + -------------------- - -------------------- +
  |                token |               amount |
  | -------------------- | -------------------- |
  |                SUSHI |               9.9989 |
  + -------------------- - -------------------- +```

**Comment by tbrand** [comment]
Yeah, so it's correct behavior.

**Comment by tbrand** [comment]
I think I can close the issue.

**Comment by kingsleyh** [comment]
yeah
