### ISSUE TITLE
Proposed change to how config works

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#175]
## Checklist
- [x] You've tried latest version of SushiChain
- [x] You've confirmed there is not a same sugestion

## Description

Currently to use config - you set up a default configuration and you can run any of the binaries and it picks up that config and you can override it with the command line as well.

I think an extra thing that would make it more awesome is this:

instead of:

```
sushi config use --name=local_sushid
sushid
sushi config use --name=local_miner
sushim
sushi config use --name=local_wallet
sushi wt amount
```

it would be nice to just override the whole config:

```
sushid --config=local_sushid
sushim --config=local_miner
sushi wt amount --config=local_wallet
```

but still get to do this (which is generally useful shortcut for day to day):
```
sushi config use --config=remote_wallet1
sushi wt amount
```
I'm happy to make a PR that explores this

**Comment by tbrand** [comment]
Agree
