### ISSUE TITLE
Landing page for a node

### ISSUE THREAD

**Issue by tbrand** [SushiChain/SushiChain#189]
## Checklist
- [x] You've tried latest version of SushiChain
- [x] You've confirmed there is not a same sugestion

## Description

Now http://testnet.sushichain.io:3000 shows a directory lists.
The page should be revised and it should contain below I think.
- Welcome message
- The landing page URL ( https://sushichain.io )
- Github・Slack・Twitter and other SNSes

Or you want make the page to blockchain explorer?
Let me know your option. 😄

**Comment by kingsleyh** [comment]
I think this should be a welcome page and links to sushichain.io and some live node stats - I can work on this if you like

**Comment by tbrand** [comment]
Yeah please :+1:

**Comment by kingsleyh** [comment]
done - pointing at API for now which seems fine
