### ISSUE TITLE
List all domains associated with an address

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#192]
Add a new command to the sushi command line binary under the `scars` option:

```
sushi scars lookup -a <address>
```

This command should list all the human readable addresses associated with this address:

```
showing human readable addresses that are mapped to the address: 
VDA4OGNjMmM5ZjkxYmQyZGFjODE3OWVkNjNkNmZjNzhlMWQ5ZWUxMDk2MzgzODVm.
 
name1.sc
name2.sc
name3.sc
```

We currently don't have any tests for the actual CLI part. But we have tests for the parts of the code which do the internal work - so the relevant tests will be in here: `./SushiChain/spec/units/dapps/scars.cr`

**Comment by tbrand** [comment]
cool

**Comment by aaronbronow** [comment]
`sushi scars lookup -a VDA2NjU5N2JlNDA3ZDk5Nzg4MGY2NjY5YjhhOTUwZTE2M2VmNjM5OWM2M2EyMWQz`

produces... 
```
 SCARS domains mapped to address VDA2NjU5N2JlNDA3ZDk5Nzg4MGY2NjY5YjhhOTUwZTE2M2VmNjM5OWM2M2EyMWQz

   Domain
 - fullmetal.sc
 - kings.sc
 - kingsley.sc
 - kh.sc
```

Remaining to do:

- [ ] tests
- [ ] api method

**Comment by kingsleyh** [comment]
done
