### ISSUE TITLE
Token support

### ISSUE THREAD

**Issue by tbrand** [SushiChain/SushiChain#20]
## Content
User of SushiCoin can create original token on it's blockchain.

**Comment by kingsleyh** [comment]
I’ve had an idea about this - we could implement this using internal dApp interface like we did scars.

The message holds the name of the token - we could then build a token exchange into the blockchain like scars domain marketplace

One thing is that I think we would need to allow people to choose the max token amount - and also to be able to distribute some of their token without having to mine it

**Comment by tbrand** [comment]
Sounds good :+1:

**Comment by kingsleyh** [comment]
after reading more about Ethereum Tokens - you can't mine tokens on Ethereum. So I think it does make sense to also not allow mining of tokens - but instead when someone creates a new token - they specify the total amount of tokens - and they are all deposited into the provided wallet. If they want to send tokens to others or use tokens within dapps they build then they get charged various fees either the same as or similar to the sushicoin fees

**Comment by kingsleyh** [comment]
I think re-using the message field in transaction might not be the best option for Token considering people may want to use their tokens with dApps - and it might be that external dApps will need to make use of this message field. So probably introducing a new field called token into a transaction would be better

**Comment by tbrand** [comment]
That's good idea. Then fee is payed by Sushi's default Token? or that Token?

**Comment by kingsleyh** [comment]
I think by sushi default token

**Comment by tbrand** [comment]
Yeah, that should be.

**Comment by tbrand** [comment]
I think I can realize your idea. Leave it to me.

**Comment by tbrand** [comment]
It's done.
