### ISSUE TITLE
Real time client integration with wallet

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#217]
## Checklist
- [x] You've tried latest version of SushiChain
- [x] You've confirmed there is not a same suggestion

## Description
Allow the real time client to have access to the wallet so it can:
* send and receive payments
* get the wallet balance for all tokens / specified token

**Comment by tbrand** [comment]
just for memo

- implement `abstract def on_message(message : String)`

**Comment by kingsleyh** [comment]
done in latest master- this is only for cli wallet - needs extra code to support a js wallet
