### ISSUE TITLE
BUG: Fix bug with loading from database

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#256]
# Problem
The difficulty is not being calculated correctly when loading a chain from the database and so the chain fails to fully load.

# Steps to re-produce
1. start a private node locally with a database
2. mine against the private node for a while
3. stop and restart the node - and see the chain does not fully load due to invalid difficulty

**Comment by kingsleyh** [comment]
This is re-lated to the current difficulty algorithm.

**Comment by jferas** [comment]
I did a little research into this and I think the problem may be rooted in these `magic numbers` in src/core/blockchain/concensus.cr

  BLOCK_TARGET_LOWER  = 10_i64
  BLOCK_TARGET_UPPER  = 40_i64
  BLOCK_AVERAGE_LIMIT =     720

Specifically BLOCK_AVERAGE_LIMIT of 720 .. I've noticed in testing that things go south consistently at block 723 .. just a few blocks after the algorithm transitions in how it computes the `current_target`.

The bug can be avoided by changing BLOCK_AVERAGE_LIMIT to a value above the current known block height (I did this just as a test), or getting rid of the 'if' that is related to BLOCK_AVERAGE_LIMIT.  This isn't the correct fix obviously... that's probably rooted in making this calculation more closely match the difficulty calculation in mining... but I thought I'd leave this info here as current progress on research.

**Comment by jferas** [comment]
So it appears that the only other place BLOCK_AVERAGE_LIMIT is used is in mining, where it is adjusted by 10 in `src/core/blockchain.cr`:
```
if block_averages.size > Consensus::BLOCK_AVERAGE_LIMIT + 10
```
Therefore when loading mined blocks from the DB, the same adjustment must be made.  Not sure why the above adjustment was done this way, but all mined blocks were done with this offset in difficulty calculation.. so to fix the above would mean that the existing chain would have to be expunged .. so the fix that works with the existing chain is to do the same adjustment to the `if` statement in the code in `src/core/blockchain/concensus.cr`

**Comment by jferas** [comment]
The correct fix is the implementation of 'Dark Gravity Wave' so that issue (250) supersedes this one.
