### ISSUE TITLE
Load the blockchain into the node quickly

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#259]
Find a solution to loading the chain into a node on node startup quickly. Progressive loading checkpoints? This is related to the issue about not holding the entire chain in memory in a node.

**Comment by jferas** [comment]
Current thinking on holding a subset of the chain in memory is that we'll hold about 2 days worth of blocks in memory, which (at an average of 2 seconds per block) is 1440 blocks.  A quick benchmark on my 2.6Ghz Intel Core i7 Macbook yields just about one minute to load and validate 1440 blocks from the database.

**Comment by kingsleyh** [comment]
done - another issue raised for securing the syncing
