### ISSUE TITLE
p2p documentation

### ISSUE THREAD

**Issue by Sphaerus** [SushiChain/SushiChain#265]
## Description
What is the project status? When can we expect more documentation? Im particularly interested in mining and building test nodes.

**Comment by kingsleyh** [comment]
Hi, currently we are in testnet but still in active development and have a lot of things still to build before we can go to mainnet. We will be re-organising the github and wiki and writing documentation and over the next couple of weeks. If you would like to get involved in anyway please feel free to join the telegram channel and message me there -> https://t.me/sushichainhq - I'll be able to give out coins and money for contributors once we get a bit further along

**Comment by kingsleyh** [comment]
This is in progress still
