### ISSUE TITLE
Correct all the English in the codebase 

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#266]
Correct all the spellings and English in the codebase - especially around error messages and command line help information

**Comment by watzon** [comment]
Working on this right now

**Comment by kingsleyh** [comment]
wow some very interesting English and strange wording in there! Great job correcting it!

**Comment by watzon** [comment]
There definitely is. Very interesting challenge.

**Comment by kingsleyh** [comment]
multi language support would be great via i18n - maybe a languages directory with a set of yaml files for each locale - and it defaults to english but you can choose your language as a command line option - sounds like it should be raised as a new issue - I'll raise it

**Comment by watzon** [comment]
That was exactly my thought. [This](https://github.com/TechMagister/i18n.cr) shard might be our best bet.

**Comment by kingsleyh** [comment]
Looks good :)

**Comment by kingsleyh** [comment]
done now
