### ISSUE TITLE
Fix all the Ameba code issues

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#269]
in the file `.ameba.yml` there are lots of failures - you must comment out sections of this file and then from the command line run `bin/ameba` to show the issues.

Then fix the issues and delete the corresponding section in the `.ameba.yml` file. The goal is to have no items left in the ameba.yml file.

**Comment by raymanoz** [comment]
We cannot currently remove all of the issues listed, as there is a bug in ameba

https://github.com/veelenga/ameba/issues/104

**Comment by raymanoz** [comment]
Another similar [bug in ameba](https://github.com/veelenga/ameba/issues/111)

**Comment by kingsleyh** [comment]
Can this one be closed now?
