### ISSUE TITLE
Change timestamps to use a human readable ISO format

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#310]
timestamps are currently Int64 - it would be nicer to have these as human readable

**Comment by kingsleyh** [comment]
leave as Int64 in core - but display better in API

**Comment by fenicks** [comment]
We can serialize timestamp (milli) to ISO8601 format https://fr.wikipedia.org/wiki/ISO_8601

**Comment by kingsleyh** [comment]
moved to notion
