### ISSUE TITLE
Forked chains between nodes allowed to exist for too long

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#315]
## Checklist
- [X] You've tried latest version of SushiChain
- [X] You've confirmed there is not a same report

## Description
Nodes that are both running miners will end up on similar 2 minute time schedules and each create new blocks, and notify their peers... but because the chains on the nodes are of same length, our current approach ignores the conflict and simply passes the new block received from a peer on to other peers, with the expectation that syncing will take place and resolve the issue.

However, with their schedules so closely synced, this scenario can exist for far too long (in one test up to a half hour)

## Environment

- Using docker: (yes or no)
no
- Crystal version: 0.30.1
- Where do you connect to?   http://testnet.sushichain.io:3000

## Command Lines and results
```
>  bin/sushid -p 4001 -w bin/testnet-wallet-1.json --testnet -d bin/local_testnet.db --private -n http://testnet.sushichain.io:3000
(and ran a miner in another shell window)
 bin/sushim -w wallets/testnet-1.json -n http://127.0.0.1:4001 --testnet
```

Result in log file attached.. note things go south at block index 578.. the first conflict but a sync isn't attempted till block index 610, over a half hour later because the chain up on testnet is the same length as the local chain.

[sync_fail.txt](https://github.com/SushiChain/SushiChain/files/3675909/sync_fail.txt)

```

**Comment by kingsleyh** [comment]
monitor this for a bit longer

**Comment by kingsleyh** [comment]
fixed
