### ISSUE TITLE
Slow spec tests related to full/partial chain testing

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#323]
## Checklist
- [X ] You've tried latest version of SushiChain
- [ X] You've confirmed there is not a same report

## Description
The execution of add_slow_blocks(1448) in some of the spec tests to emulate what happens for 2 full days of data really makes the spec tests run slow

## Environment

- Using docker: (yes or no)
- Crystal version: 0.30.1

## Command Lines and results
crystal spec
(wait a long time for success)
its dog slow!

**Comment by kingsleyh** [comment]
fixed
