### ISSUE TITLE
REST controller is returning the in-memory chain... not the full chain

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#324]
## Checklist
- [x ] You've tried latest version of SushiChain
- [x ] You've confirmed there is not a same report

## Description
Failed in the process of doing a `crystal spec` after making some changes so that we only hold 2 hours (60 blocks) in memory as part of speeding things up to address this issue: https://github.com/SushiChain/SushiChain/issues/323.

2 Rest controller tests that add 200 blocks failed because the rest controller wasn't returning the whole chain.. only the in-memory subset.

## Environment

- Using docker: no
- Crystal version: 0.30.1
- Where do you connect to? (http://testnet.sushichain.io:3000, http://localhost:300 or so on)

## Command Lines and results
crystal spec

**Comment by kingsleyh** [comment]
I think in the long term calls like this will have to be paginated - so when we have 10 million blocks - we can by default return the 2 days worth from in memory - and then paginate to get more - similar to how transactions_for_address works

**Comment by kingsleyh** [comment]
fixed
