### ISSUE TITLE
Add FAST blocks to e2e test

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#333]
## Checklist
- [ #] You've tried latest version of SushiChain
- [ #] You've confirmed there is not a same sugestion

## Description
The e2e test isn't testing the FAST block feature

**Comment by jferas** [comment]
This involves adding the developer fund to the nodes started by e2e.. which surfaced a bug related to the transactions in the genesis block.

**Comment by kingsleyh** [comment]
done
