### ISSUE TITLE
Validate a random selection of the blocks in the blockchain when loaded from the DB or when synced from the network.

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#334]
## Checklist
- [* ] You've tried latest version of SushiChain
- [*] You've confirmed there is not a same sugestion

## Description
We should check for validation blocks that are loaded from the database or are synced from the network.. with the strategy being "check the first 50 blocks.. check the last 50 blocks, and check a random sample of 10 percent of the blocks in between (the 10 percent can be configurable.. definitely in the source code if not by command line argument to sushid).

**Comment by kingsleyh** [comment]
done
