### ISSUE TITLE
Clean up genesis block transaction differences related to developer fund

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#335]
## Checklist
- [ *] You've tried latest version of SushiChain
- [ *] You've confirmed there is not a same sugestion

## Description
The transaction in the genesis block for developer fund is both timestamped and created with a random ID, which means that the 3 nodes in the e2e test have different hashes for the genesis block.. which means that their prev_hash values in block 2 all disagree... which puts the e2e test in a terrible state right from the start.   For now I have resolved this by modifying the self.transactions method in developer_fund.cr specify a zero for transaction time, and "developer_fund" for the transaction ID... but I think the whole idea of nodes starting up with a developer fund independently via command line option might need to be revisited.. the developer fund should come in the genesis block from the network, or from the database.. but if a node is connected to a network, it probably shouldn't write an original genesis block.. it should get the one from the network if its DB is empty.   The ability for different nodes to start with different idea of developer fund content seems like it could be problematic.

**Comment by kingsleyh** [comment]
I agree. If the node is connecting to another node - it should fetch the genesis block from that node when it's syncing. If it's a standalone node then it can write it's own genesis block.

We should also test some cases - where someone starts with a standalone node and then tries to connect it to an existing network - to make sure we correctly enforce that the node replaces it's whole chain with that from the remote network.

**Comment by kingsleyh** [comment]
moved to notion
