### ISSUE TITLE
General solution needed for dapp data storage in database

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#341]
## Checklist
- [ ] You've tried latest version of SushiChain
- [ ] You've confirmed there is not a same report

## Environment

- Using docker: (yes or no)
- Crystal version: x.x.x
- Where do you connect to? (http://testnet.sushichain.io:3000, http://localhost:300 or so on)

## Command Lines and results

```bash
> [your command]
[the result]
```

**Comment by jferas** [comment]
Currently the dapp/buildin data structures (including, but not limited to indices, scars, token, transaction, and utx0) are all held in memory.  We need a general solution for all dapps to store and retrieve their data from permanent storage for long term scalability.

**Comment by jferas** [comment]
Like all the other blockchain structures.. keep some subset in memory and the entirety of the data in the DB

**Comment by kingsleyh** [comment]
Circle back to this when doing SMART ASSETS

**Comment by kingsleyh** [comment]
moved to notion
