### ISSUE TITLE
Nonce type must be signed integer

### ISSUE THREAD

**Issue by fenicks** [SushiChain/SushiChain#342]
After Crystal 0.30.1 an `Arithmetic overflow` error is happening when retrieving the nonce on other tools like the SushiChain Explorer. Some nonces are signed but type is UInt64.

## Environment
- GNU/Linux Ubuntu 18.04_x64
- Crystal version: 0.32.1

**Comment by kingsleyh** [comment]
When does this happen? When parsing the json?

**Comment by fenicks** [comment]
When parsing JSON looks Ok even if nonce is signed which is strange. But it happen when I store signed nonce into the database and only with crystal 0.31.1+.

**Comment by fenicks** [comment]
I'm trying a version of SushiChain with nonce typed as Int64 but I don't know if it's a good thing when I read this comment: https://github.com/SushiChain/SushiChain/blob/d313055db15096c92df4c702f109de82a5130449/spec/utils/node.cr#L74

**Comment by fenicks** [comment]
Looks like SuchiChain is returning the correct nonce with JSON.parse. It works as expected, the problem is only how RethinkDB driver deals with UInt64 with crystal v0.31.1+.
