### ISSUE TITLE
Reject fast transactions when chain not mature enough / no leader node

### ISSUE THREAD

**Issue by jferas** [SushiChain/SushiChain#343]
## Checklist
- [ x] You've tried latest version of SushiChain
- [ x] You've confirmed there is not a same sugestion

## Description
Currently, when a fast transaction is sent into the network, if the chain is not mature enough (not enough slow blocks and/or no leader) the transactions are dropped onto the floor.

The dropped transactions should instead be added to the "rejected" transaction storage.

**Comment by kingsleyh** [comment]
done
