### ISSUE TITLE
Implement Dapp support

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#35]
Implement infrastructure to allow developers to build Dapps on SushiCoin in a similar way to Ethereum or Neo

**Comment by tbrand** [comment]
This is my idea, any comments are welcome!

Our blockchain as a platform of dApps should have features like these.

- **Evidence**
Transaction contains fixed length hash, that will be an evidence for the data is correct.
User can record the evidence onto our blockchain by creating the transaction. (with a little bit fees.)

- **Sending/Recieving data**
Sending data from a node to a node by their id.
It costs according to the data size with a little bit fees.

- **Creating token**
Creating arbitrary tokens.
SushiCoin will be one of them but creating by default.

---

Let me try to create a data sharing dApps from this idea.

- Uploader via dApps create a transaction to share a file with their evidence hash and file's title as a message of transaction.
- dApps makes a list of these files.
- If donwloader want to get the file, request it to the dApps by creating a transaction that includes target file's id (transaction id), downloading fee and transaction fee. (The dApps does monetize like this.)
- The donwloader recieve the file and check the evidence hash.
- dApps kickbacks some of tokens to the original uploader.

```
Uploader                                               Reciever
Uploader --- upload files --->       -- send files --> Reciever
Uploader                       dApps                   Reciever
Uploader <-- kickback token --       <--- pay fees --- Reciever
Uploader                                               Reciever
```

**Comment by kingsleyh** [comment]
See Issue #74 for my idea of a dApp

**Comment by kingsleyh** [comment]
I would also like to build an identity resolution dApp similar to Civic or uPort - so that you can register an identity which is stored in the blockchain which you can use as a proof of identity which can be used to log into other applications. So instead of Facebook/Google holding everybody's log in data and other sensitive data - you can manage it yourself and choose what data you allow to be released from your identity for different things.

This identity could be optionally KYC'd (Know Your Customer) using official documents e.g passport / drivers license so that KYC'd identities can be trusted to do extra things like buying digital currency immediately. The blockchain holds the proof that the identity exists and can be trusted - even though the identity is anonymous. (if KYC'd the identity is less anonymous because the official documents were matched with the identity during the KYC process - ideally this cross reference would be discarded after KYC is complete - but depending on who is doing the KYC this might not be enforcable - not sure)

**Comment by tbrand** [comment]
OK, let me close this issue. If you want to improve it, please open others.
