### ISSUE TITLE
[RFC] Refactor RPC Controller to have commands as separate classes

### ISSUE THREAD

**Issue by watzon** [SushiChain/SushiChain#55]
The way the rpc controller works currently all of the commands are stored in one controller. This works of for the small amount of commands that exist currently, but as more methods are added the controller is going to become quite bloated.

I propose that we allow the rpc_controller to be changed into more of an rpc_router which routes commands to the appropriate controller. The controllers would each define the arguments and flags they take, their description, command signature, etc. In this way the cli would only have to have cli specific commands, and if the cli is connected to a node it can list the commands that the node accepts as well.

The following is what I'd imagine an RpcCommand looking like:

```crystal
module ::Sushi::Core::Controllers
  abstract class RpcCommand
    include ArgParser

    abstract def call(json, context, params)

  end

  class CreateUnsignedTransaction < RpcCommand

    command_name "createunsignedtransaction"
    
    argument sample : String,
      required: true

    flag debug : Bool,
      short: "-d"

    def call(json, context, params)
      action = json["action"].to_s
      senders = Models::Senders.from_json(json["senders"].to_s)
      recipients = Models::Recipients.from_json(json["recipients"].to_s)
      message = json["message"].to_s

      transaction = @blockchain.create_unsigned_transaction(
        action,
        senders,
        recipients,
        message,
      )

      fee = transaction.calculate_fee

      raise "Invalid fee #{fee} for the action #{action}" if fee <= 0.0

      context.response.print transaction.to_json
      context
    end

  end
end
```

**Comment by tbrand** [comment]
Seems good! Sending us the Pull Request! :+1:
