### ISSUE TITLE
Twitter integrated feature

### ISSUE THREAD

**Issue by tbrand** [SushiChain/SushiChain#60]
Twitter integrated rewards is very effective for the promotion.
- RT our tweet -> 1 SushiCoin
- Send SushiCoins a.k.a. tips.
- Create wallet.
and so on.

These are many things to be discussed. (How to integrate? How to manage secret keys? and so on.)
But I want to keep this open as just one of the idea.

**Comment by kingsleyh** [comment]
revisit later on
