### ISSUE TITLE
Node strange issues

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#72]
Here are a few node issues which happened when running - not sure why they happened yet. But tracking them here so we can fix.

1. Closed stream and invalid nonce on standalone node (when only running 1 miner with 2 nodes started up (1 standalone, 2 connected to standalone)
<img width="1055" alt="screen shot 2018-02-14 at 05 17 55" src="https://user-images.githubusercontent.com/103770/36189900-e420b346-114c-11e8-96bb-be62e175d042.png">

2. Unhandled exception (I think this happened on the standalone node when a node connected to it was stopped)
<img width="986" alt="screen shot 2018-02-14 at 05 18 47" src="https://user-images.githubusercontent.com/103770/36189935-176c6b46-114d-11e8-96a4-0d96ab22948f.png">

**Comment by tbrand** [comment]
I'll try to recreate the situation. Thanks
