### ISSUE TITLE
Javascript / Electron Wallet

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#82]
provide at least 1 non Crystal Wallet.

I've done most of the ground work for a Javascript based Wallet. The Elm language is my strong point - so thinking of creating an Electron or Web wallet using Elm.

**Comment by watzon** [comment]
I could potentially take this on. I am experimenting with the idea of using Dart + Flutter as that combination currently supports web and mobile and will very soon support desktop as well.

**Comment by kingsleyh** [comment]
Kostas will pick up continuing with the Electron version and will re-write in React/Typescript

**Comment by kingsleyh** [comment]
moved to notion
