### ISSUE TITLE
Coin denominations

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#95]
If 1 coin is worth £1000 and I want to send only $10 worth of coin to an address we could perhaps follow a similar strategy to Ethereum:

https://steemit.com/cryptocurrency/@encryptcy/ethereum-denominations

**Comment by tbrand** [comment]
Maybe it's gonna be a next big changes for SushiChain.

**Comment by kingsleyh** [comment]
Here is my proposal:

1. We continue to store amounts as UInt64 and we represent the amount with a custom class so that the last 8 digits represent 8 decimal places:

```
800,000,000 (800 million) SHARI becomes 8.00000000 (8)
```

We always display and make calculations using the Amount class which represents the 8 digits as 8 decimal places.

A proposed coin denomination could be:

```coin denominations:

1 Shiso  = 0.00000001
1 Egoma  = 0.00000100
1 Onomi  = 0.00010000
1 Azuki  = 0.01000000
1 Shari  = 1
1 Kuri   = 100
1 Mizuna = 1000
1 Saba   = 10000
1 Maguro = 100000
1 Suzuki = 1000000
```

**Comment by kingsleyh** [comment]
we can apply the same logic to all amounts including Tokens - but people can use whatever names they like for amounts of tokens.

**Comment by kingsleyh** [comment]
might be able to use BigDecimal here:    https://crystal-lang.org/api/master/BigDecimal.html
